[package]
name = "bom-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
cargo-bom = { path = "../cargo-bom" }
clap = { version = "4.5.4", features = ["derive"] }
cyclonedx-bom = "0.5.0"
semver = "1.0"
serde_json = "1.0.83"


