[package]
name = "allow-list"
version = "0.3.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.81"
cargo_metadata = "0.19"
clap = { version = "4.5.4", features = ["derive"] }
cyclonedx-bom = "0.8.0"
semver = "1.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.83"
spdx = "0.10.8"
time = { version = "0.3.41", features = ["formatting"] }
toml = "0.8"


