[package]
name = "allow-list"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
cyclonedx-bom = "0.5.0"
semver = "1.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.83"


